### ISSUE TITLE
api使用错误

### ISSUE THREAD

**Issue by Mamong** [94xy/miniprogram-privacy#1]
1.点击查看指引不是必须的，建议加个控制
2.如果是主动显示，那么只要按钮类型对就行
3.如果是接口触发的，需要注册wx.onNeedPrivacyAuthorization，并且调用resolvePrivacyAuthorization来继续执行接口。
4.拒绝不应该简单退出，应该可以注册回调

**Comment by Mamong** [comment]
这玩意挺麻烦的啊，看起来。如果支持回调的话，每个可能触发的页面都得引入组件。

**Comment by 94xy** [comment]
在此之前没有任何开源经验，我研究一下如何处理 issue，先回复：
这里面应该是没有错误的：
1. 稍后加一个是否选择强制查看指引；
2. 没太看懂；
3. 组件里面都有的，这样外部可以有更少的代码， Page onShow 中的 getPrivacySetting 只需要控制组件显示隐藏即可，这样可以保证用户拒绝后从后台再次打开小程序也能触发组件生命周期；
4. 稍后看一下，前期考虑的是绝大部分开发者都没有写全隐私接口调用失败的回调函数，用户拒绝后所有隐私接口直接没有反应的、没有任何提示，不如直接拒绝用户使用
5. 应该是没有什么好办法，每个使用隐私接口的页面都需要加

**Comment by Mamong** [comment]
issue主要是讨论下问题，并不需要怎么处理。
我刚才仔细研究了下微信的API，发现你的使用有误。主要是注册这个接口：https://developers.weixin.qq.com/miniprogram/dev/api/open-api/privacy/wx.onNeedPrivacyAuthorization.html，除非你放弃用它。如我前面所言，隐私指引，你可以主动弹出，让用户去点这个特殊的同意按钮；也可以被动在相关接口触发的时候显示，这是后需要调用resolve，确保接口可以成功或者失败。

**Comment by 94xy** [comment]
> issue主要是讨论下问题，并不需要怎么处理。 我刚才仔细研究了下微信的API，发现你的使用有误。主要是注册这个接口：[https://developers.weixin.qq.com/miniprogram/dev/api/open-api/privacy/wx.onNeedPrivacyAuthorization.html，除非你放弃用它。如我前面所言，隐私指引，你可以主动弹出，让用户去点这个特殊的同意按钮；也可以被动在相关接口触发的时候显示，这是后需要调用resolve，确保接口可以成功或者失败。](https://developers.weixin.qq.com/miniprogram/dev/api/open-api/privacy/wx.onNeedPrivacyAuthorization.html%EF%BC%8C%E9%99%A4%E9%9D%9E%E4%BD%A0%E6%94%BE%E5%BC%83%E7%94%A8%E5%AE%83%E3%80%82%E5%A6%82%E6%88%91%E5%89%8D%E9%9D%A2%E6%89%80%E8%A8%80%EF%BC%8C%E9%9A%90%E7%A7%81%E6%8C%87%E5%BC%95%EF%BC%8C%E4%BD%A0%E5%8F%AF%E4%BB%A5%E4%B8%BB%E5%8A%A8%E5%BC%B9%E5%87%BA%EF%BC%8C%E8%AE%A9%E7%94%A8%E6%88%B7%E5%8E%BB%E7%82%B9%E8%BF%99%E4%B8%AA%E7%89%B9%E6%AE%8A%E7%9A%84%E5%90%8C%E6%84%8F%E6%8C%89%E9%92%AE%EF%BC%9B%E4%B9%9F%E5%8F%AF%E4%BB%A5%E8%A2%AB%E5%8A%A8%E5%9C%A8%E7%9B%B8%E5%85%B3%E6%8E%A5%E5%8F%A3%E8%A7%A6%E5%8F%91%E7%9A%84%E6%97%B6%E5%80%99%E6%98%BE%E7%A4%BA%EF%BC%8C%E8%BF%99%E6%98%AF%E5%90%8E%E9%9C%80%E8%A6%81%E8%B0%83%E7%94%A8resolve%EF%BC%8C%E7%A1%AE%E4%BF%9D%E6%8E%A5%E5%8F%A3%E5%8F%AF%E4%BB%A5%E6%88%90%E5%8A%9F%E6%88%96%E8%80%85%E5%A4%B1%E8%B4%A5%E3%80%82)

使用无误，不仅不能放弃而且必须用它，否则用户点同意按钮也无法同步给微信；使用隐私接口时触发只会让这件事变得更加复杂，你可以试一下，**另外，刚发现组件可以使用页面的生命周期，也就是只需要引入组件即可，不需要在 Page onShow 中加个 getPrivacySetting，稍后上传**

**Comment by 94xy** [comment]
刚更新了一下：
1. 现在只需要引入组件即可，不再需要多余代码；
2. 增加了跳过阅读选项，暂未找到组件判断是否设置了回调函数的方法；
3. 目前还是点击拒绝直接退出小程序，之后有找到方法再更新

**Comment by Mamong** [comment]
就是你主动弹引导页，然后用户点确定，这时候是不会触发onNeedPrivacyAuthorization，更没有resolve了，所以你同意回调里不能调用它，你自己打断点看看。

**Comment by 94xy** [comment]
> 就是你主动弹引导页，然后用户点确定，这个时候是不会触发onNeedPrivacyAuthorization，更没有解决了，所以你同意回调里不能调用它，你自己打断点看看。

抱歉，是我之前没搞明白，重新研究了一遍文档，现在知道了，不需要使用 wx.onNeedPrivacyAuthorization 接口，只需要按钮就可以搞定这件事

**Comment by Mamong** [comment]
嗯，在入口主动检测和弹窗，这种是最简单暴力的做法。如果要做API触发的话，就非常麻烦，要去每个页面都埋一下。
